/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    copy: typeof import('./src/components/ListingCard copy.vue')['default']
    FeatureIcon: typeof import('./src/components/FeatureIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListingCard: typeof import('./src/components/ListingCard.vue')['default']
    PropertyCard: typeof import('./src/components/PropertyCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
